(ns apollo.constants-test)

(def apl-testscore
    '({:instrument "Acoustic Grand Piano"
    :instrument-number 0
    :octave 4
    :channel 0
    :notes
    [{:note "c"
      :midi-note (60)
      :volume 60
      :offset 4
      :channel 0
      :duration 4}
     {:note "d"
      :midi-note (62)
      :volume 60
      :offset 8
      :channel 0
      :duration 4}
     {:note "e"
      :midi-note (64)
      :volume 60
      :offset 12
      :channel 0
      :duration 4}
     {:note "f"
      :midi-note (65)
      :volume 60
      :offset 16
      :channel 0
      :duration 2}
     {:note "g"
      :midi-note (67)
      :volume 60
      :offset 18
      :channel 0
      :duration 2}
     {:note "a"
      :midi-note (69)
      :volume 60
      :offset 20
      :channel 0
      :duration 2}
     {:note "b"
      :midi-note (71)
      :volume 60
      :offset 22
      :channel 0
      :duration 2}
     {:note "c"
      :midi-note (60)
      :volume 60
      :offset 24
      :channel 0
      :duration 2}
     {:note "c"
      :midi-note (60)
      :volume 60
      :offset 26
      :channel 0
      :duration 2}
     {:note "b"
      :midi-note (71)
      :volume 60
      :offset 28
      :channel 0
      :duration 2}
     {:note "a"
      :midi-note (69)
      :volume 60
      :offset 30
      :channel 0
      :duration 2}
     {:note "g"
      :midi-note (67)
      :volume 60
      :offset 32
      :channel 0
      :duration 2}
     {:note "f"
      :midi-note (65)
      :volume 60
      :offset 34
      :channel 0
      :duration 2}
     {:note "e"
      :midi-note (64)
      :volume 60
      :offset 36
      :channel 0
      :duration 2}
     {:note "d"
      :midi-note (62)
      :volume 60
      :offset 38
      :channel 0
      :duration 2}
     {:note "c"
      :midi-note (60)
      :volume 60
      :offset 40
      :channel 0
      :duration 2}]}))