title = "Apollo"
baseURL = "https://senyosimpson.github.io/apollo/"
languageCode = "en-us"
theme = "aether"
publishdir = "../"

[params]
    brand = "Apollo"
    description = "A music programming language built in Clojure"
    bgimg = "/images/ignasi_pattern_s.png"

[markup]
  [markup.highlight]
    style = "igor"